test-3_container-staging_app_77dfcf4_env_295026d.yaml Updated

diff --git a/.github/workflows/test-3_container-staging_app_77dfcf4_env_295026d.yaml b/.github/workflows/test-3_container-staging_app_77dfcf4_env_295026d.yaml
--- a/.github/workflows/test-3_container-staging_app_77dfcf4_env_295026d.yaml
+++ b/.github/workflows/test-3_container-staging_app_77dfcf4_env_295026d.yaml
@@ -82,7 +82,7 @@ jobs:
                   if jq -e '.Results | map(select(.Vulnerabilities)) | length > 0' trivy_results.min.json >/dev/null; then
                     echo "Vulnerabilities detected!"
                     jq '.Results[] | select(.Vulnerabilities?) | {Target: .Target, Vulnerabilities: .Vulnerabilities[] | {ID: .VulnerabilityID, Severity: .Severity, Description: .Description}}' trivy_results.min.json
-                    exit 1
+                    echo "IS_TRIVY_VULNERABILITIES_DETECTED=true" >> $GITHUB_ENV
                   fi
                   
       - name: 'Run :: Trivy Filesystem Scan (Including Trivy Ignores)'
@@ -145,6 +145,12 @@ jobs:
 
                   else
                       echo ".trivyignore file not found"
+                  fi
+                  trivyVulnFound=${{ env.IS_TRIVY_VULNERABILITIES_DETECTED }}
+                  if [ -n "$trivyVulnFound" ]; then
+                    echo "Trivy vulnerabilities were detected."
+                    echo "The job failed after uploading the code scan reports."
+                    exit 1
                   fi
                   
   _status-pending:
@@ -763,6 +769,7 @@ jobs:
             
     needs:
       - build-and-push
+      - _status_testing
     permissions: write-all
     if: >-
       needs.build-and-push.outputs.stepsCanProceed == 'true' &&
